### ISSUE TITLE
数据安全问题

### ISSUE THREAD

**Issue by rambo-panda** [aleechou/meteor-doc-cn#3]
meteor简洁的开发方式，前端化的bug调试 这些优点真的太棒了。 
但是有一个很大疑问？？？  meteor 如何保证数据 接口的安全性？  因为我所有的逻辑，都可以再调试工具中得到。这样做太危险了。
meteor 据说以后会开发出 用户权限验证问题。  但是即便有了这套验证系统，他的安全性真的很令人担忧。

你是怎么解决这个问题的

**Comment by bigzhu** [comment]
meteor早就没有所谓的安全问题了.
仔细阅读下 meteor 的文档,把调试开发的自动同步包去掉.
meteor 的安全相当完善了,而且和一般的 http 开发没什么区别,能返回哪些数据,都可以由开发者根据各种条件,自行定制.

**Comment by rambo-panda** [comment]
一直习惯自己用linux自动化脚本 部署初始化项目。  以前听说过又meteor  以及 yo等自动部署工具。 一直没来得及了解。  前些日子见到朋友开源私人博客用meteor 感觉 听清新的。  希望能跟你一起学习学习 毕竟这玩意 中文帮助文档 太少太少了。 meteor 依你之见 现在适合应用在 产品环境吗？
